vich_uploader:
    db_driver: orm

    mappings:
        user_pictures:
            uri_prefix: /images/userPictures
            upload_destination: '%kernel.project_dir%/public/images/userPictures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer